Fix typo

diff --git a/home/.git_templates/hooks/pre-commit b/home/.git_templates/hooks/pre-commit
--- a/home/.git_templates/hooks/pre-commit
+++ b/home/.git_templates/hooks/pre-commit
@@ -18,7 +18,7 @@ if [ $? -eq 0 ]; then
 
       git diff --cached -U0 | grep -i "$word" > /dev/null
       if [ $? -eq 0 ]; then
-        echo "Can't commit because of including the prolibited word '$word'" >&2
+        echo "Can't commit because of including the prohibited word '$word'" >&2
         exit 1
       fi
     done < ~/.git_prohibited_words
